config/routes.rb
Rails.application.routes.draw do
  resources :cloth_transmissions
  resources :transmissions
  resources :cloths
  resources :people
  resources :brands
  resources :cloth_types
  devise_for :users
  resources :appointments
  resources :guards
  resources :workers
  resources :medical_centers
  resources :worker_types
  resources :medical_center_types
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'people#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in

    # Si hay ID es porque hay usuario logueado, mientras que es un usuario "invitado" en memoria, no tiene ID.
    unless user.id.nil?
      can :manage, :all

    else
      # Ver listado Centros
      can :index, MedicalCenter
      # Crear Nuevo Usuario
      can :create, User
      # Ver / Actualizar SOLO SUS DATOS
      can :read, User, :id => user.id
      can :update, User, :id => user.id
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :worker
  belongs_to :medical_center

  validate :medic
  validate :appointments_overlapping_with_guard

  def medic
    unless self.worker.worker_type_id == 1
      self.errors.add(:worker_type_id, "Sólo puede asignarse turnos a los médicos")
    end
  end


  def appointments_overlapping_with_guard
    # Recorro las guardias en búsqueda de coincidencias
    Guard.all.each do |guard|
      # SI la fecha del turno está entre el inicio y fin de una fecha de guardia, y conicide con el trabajador del turno y la guardia, agrego el error y corto el ciclo.
      if self.appointment_date.between?(guard.guard_date.beginning_of_day, guard.guard_date.end_of_day) && (self.worker.id == guard.worker.id)
        puts "*** El turno se solapa con una guardia (ID de Guardia: #{guard.id}) *** "
        errors.add(:appointment_date, 'Este Médico NO PUEDE recibir turnos en un día de GUARDIA')
        break
      end
    end
    puts "*** Turno Asignado con Éxito ***"
  end
end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/models/cloth.rb
class Cloth < ApplicationRecord
  belongs_to :clothing_type
  belongs_to :brand

  paginates_per 10
end

app/models/cloth_transmission.rb
class ClothTransmission < ApplicationRecord
  belongs_to :cloth
  belongs_to :transmission
end

app/models/cloth_type.rb
class ClothType < ApplicationRecord
end

app/models/guard.rb
class Guard < ApplicationRecord
  belongs_to :worker
  belongs_to :medical_center

  validate :overlapping_guard


  def guard_worker
    worker.full_name
  end

  def overlapping_guard
    # Recorro las guardias en búsqueda de coincidencias
    Guard.all.each do |guard|
      # SI la fecha del turno está entre el inicio y fin de una fecha de guardia, y conicide con el trabajador del turno y la guardia, agrego el error y corto el ciclo.
      if self.appointment_date.between?(guard.guard_date.beginning_of_day, guard.guard_date.end_of_day) && (self.worker.id == guard.worker.id)
        puts "*** El turno se solapa con una guardia (ID de Guardia: #{guard.id}) *** "
        errors.add(:appointment_date, 'Este Médico NO PUEDE recibir turnos en un día de GUARDIA')
        break
      end
    end
    puts "*** Turno Asignado con Éxito ***"
  end
end

app/models/medical_center.rb
class MedicalCenter < ApplicationRecord
  belongs_to :medical_center_type
  has_many :guards

  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
end

app/models/person.rb
class Person < ApplicationRecord



  def full_name
    first_name + " " + last_name
  end

end

app/models/transmission.rb
class Transmission < ApplicationRecord
  belongs_to :person
  has_many :cloths, :througth => :cloth_transmissions

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/worker.rb
class Worker < ApplicationRecord
  belongs_to :worker_type

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone_number, presence: true
  validates :email, presence: true
  validates :worker_type, presence: true

  def full_name
    first_name + " " + last_name
  end

end

app/models/worker_type.rb
class WorkerType < ApplicationRecord
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/cloths_helper.rb
module ClothsHelper
end

app/helpers/guards_helper.rb
module GuardsHelper

  def guard_status(guard)
  if (guard.appointment_date < Time.now)
    return 'table-danger'
  elsif (guard.appointment_date >= Time.now)
    return 'table-success'
  end
end

end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/shared/_footer.html.erb
<nav class="navbar fixed-bottom navbar-dark bg-warning">
  <%= link_to "Inicio", root_url, class: 'btn btn-sm bg-light' %>
  <a id="copyright" class="navbar-brand" href="#!"><small>Amiel<strong>Rostán</strong> &copy; 2021 - Programación III - UAP</small></a>
</nav>

app/views/shared/_main_menu.html.erb
<div class="collapse navbar-collapse show" id="navbarWithDropdown">
  <ul class="navbar-nav">
    <li class="nav-item">
      <%= link_to "Inicio", root_url, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to "presentadores", people_url, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to "marcas", brands_url, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to "tipos de vestimnenta", cloth_types_url, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to "vestimnenta", cloths_url, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to "transmisiones", transmissions_url, class: 'nav-link' %>
    </li>
    <!-- Dropdown -->
    <!-- <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href=" <%#= categories_url %>" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">Categorías</a>
      <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <li><%#= link_to "Editar Categorias", categories_url, class: 'dropdown-item' %></li>
        <%# Category.all.each do |cat| %>
          <li><%#= link_to cat.name, store_products_url(category: cat.id), class: 'dropdown-item' %></li>
        <%# end %>
      </ul>
    </li> -->
  </ul>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-secondary">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_url %>">Sanatorio wap</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <%= render 'shared/main_menu' %>

    <%= render 'shared/user_menu' %>

  </div>
</nav>

app/views/shared/_user_menu.html.erb
<div class="collapse navbar-collapse show" id="navbarWithDropdown">
  <ul class="navbar-nav">
    <% if user_signed_in? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle btn btn-secondary " href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <span style="color:white"><%= current_user.email %></span>
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <li><%= link_to "Editar Perfil", edit_user_registration_path, class: "btn" %></li>
          <hr>
          <li><%= link_to "Cerrar Sesión", destroy_user_session_path, class: "btn",  method: :delete  %></li>
        </ul>
      </li>
    <% else %>
      <%= link_to "Iniciar Sesión", new_user_session_url, class: 'btn btn-success' %>
    <% end %>
  </ul>
</div>