config/routes.rb
Rails.application.routes.draw do
  resources :cloth_transmissions
  resources :transmissions
  resources :cloths
  resources :people
  resources :brands
  resources :cloth_types
  devise_for :users
  resources :appointments
  resources :guards
  resources :workers
  resources :medical_centers
  resources :worker_types
  resources :medical_center_types
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'people#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in

    # Si hay ID es porque hay usuario logueado, mientras que es un usuario "invitado" en memoria, no tiene ID.
    unless user.id.nil?
      can :manage, :all

    else
      # Ver listado Centros
      can :index, MedicalCenter
      # Crear Nuevo Usuario
      can :create, User
      # Ver / Actualizar SOLO SUS DATOS
      can :read, User, :id => user.id
      can :update, User, :id => user.id
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :worker
  belongs_to :medical_center

  validate :medic
  validate :appointments_overlapping_with_guard

  def medic
    unless self.worker.worker_type_id == 1
      self.errors.add(:worker_type_id, "Sólo puede asignarse turnos a los médicos")
    end
  end


  def appointments_overlapping_with_guard
    # Recorro las guardias en búsqueda de coincidencias
    Guard.all.each do |guard|
      # SI la fecha del turno está entre el inicio y fin de una fecha de guardia, y conicide con el trabajador del turno y la guardia, agrego el error y corto el ciclo.
      if self.appointment_date.between?(guard.guard_date.beginning_of_day, guard.guard_date.end_of_day) && (self.worker.id == guard.worker.id)
        puts "*** El turno se solapa con una guardia (ID de Guardia: #{guard.id}) *** "
        errors.add(:appointment_date, 'Este Médico NO PUEDE recibir turnos en un día de GUARDIA')
        break
      end
    end
    puts "*** Turno Asignado con Éxito ***"
  end
end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/models/cloth.rb
class Cloth < ApplicationRecord
  belongs_to :clothing_type
  belongs_to :brand

  paginates_per 10
end

app/models/cloth_transmission.rb
class ClothTransmission < ApplicationRecord
  belongs_to :cloth
  belongs_to :transmission
end

app/models/cloth_type.rb
class ClothType < ApplicationRecord
end

app/models/guard.rb
class Guard < ApplicationRecord
  belongs_to :worker
  belongs_to :medical_center

  validate :overlapping_guard


  def guard_worker
    worker.full_name
  end

  def overlapping_guard
    # Recorro las guardias en búsqueda de coincidencias
    Guard.all.each do |guard|
      # SI la fecha del turno está entre el inicio y fin de una fecha de guardia, y conicide con el trabajador del turno y la guardia, agrego el error y corto el ciclo.
      if self.appointment_date.between?(guard.guard_date.beginning_of_day, guard.guard_date.end_of_day) && (self.worker.id == guard.worker.id)
        puts "*** El turno se solapa con una guardia (ID de Guardia: #{guard.id}) *** "
        errors.add(:appointment_date, 'Este Médico NO PUEDE recibir turnos en un día de GUARDIA')
        break
      end
    end
    puts "*** Turno Asignado con Éxito ***"
  end
end

app/models/medical_center.rb
class MedicalCenter < ApplicationRecord
  belongs_to :medical_center_type
  has_many :guards

  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
end

app/models/medical_center_type.rb
class MedicalCenterType < ApplicationRecord
end

app/models/person.rb
class Person < ApplicationRecord



  def full_name
    first_name + " " + last_name
  end

end

app/models/transmission.rb
class Transmission < ApplicationRecord
  belongs_to :person
  has_many :cloths, :througth => :cloth_transmissions

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/worker.rb
class Worker < ApplicationRecord
  belongs_to :worker_type

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone_number, presence: true
  validates :email, presence: true
  validates :worker_type, presence: true

  def full_name
    first_name + " " + last_name
  end

end

app/models/worker_type.rb
class WorkerType < ApplicationRecord
end

app/controllers/cloths_controller.rb
class ClothsController < ApplicationController
  before_action :set_cloth, only: %i[ show edit update destroy ]

  # GET /cloths or /cloths.json
  def index
    @cloths = Cloth.all
    @cloths = @cloths.select(:brand).map(&:brand).uniq
    @cloths = @cloths.select(:clothing_type).map(&:clothing_type).uniq
    @cloths = @cloths.where(["description LIKE :filter", :filter => "%" + params[:filter] + "%"]) unless params[:filter].blank?
    @cloths = @cloths.order(:name).page params[:page]
  end

  # GET /cloths/1 or /cloths/1.json
  def show
  end

  # GET /cloths/new
  def new
    @cloth = Cloth.new
  end

  # GET /cloths/1/edit
  def edit
  end

  # POST /cloths or /cloths.json
  def create
    @cloth = Cloth.new(cloth_params)

    respond_to do |format|
      if @cloth.save
        format.html { redirect_to @cloth, notice: "Cloth was successfully created." }
        format.json { render :show, status: :created, location: @cloth }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cloth.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cloths/1 or /cloths/1.json
  def update
    respond_to do |format|
      if @cloth.update(cloth_params)
        format.html { redirect_to @cloth, notice: "Cloth was successfully updated." }
        format.json { render :show, status: :ok, location: @cloth }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cloth.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cloths/1 or /cloths/1.json
  def destroy
    @cloth.destroy
    respond_to do |format|
      format.html { redirect_to cloths_url, notice: "Cloth was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cloth
      @cloth = Cloth.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cloth_params
      params.require(:cloth).permit(:name, :color, :description, :clothing_type_id, :brand_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/cloth_types_helper.rb
module ClothTypesHelper
end

app/helpers/cloths_helper.rb
module ClothsHelper
end

app/helpers/guards_helper.rb
module GuardsHelper

  def guard_status(guard)
  if (guard.appointment_date < Time.now)
    return 'table-danger'
  elsif (guard.appointment_date >= Time.now)
    return 'table-success'
  end
end

end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/cloths/_form.html.erb
<%= form_with(model: cloth) do |form| %>
  <% if cloth.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cloth.errors.count, "error") %> prohibited this cloth from being saved:</h2>

      <ul>
        <% cloth.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :clothing_type_id %>
    <%= form.collection_select(:clothing_type_id, ClothingType.all, :id, :name )   %>
  </div>

  <div class="field">
    <%= form.label :brand_id %>
    <%= form.collection_select(:brand_id, Brands.all, :id, :name )   %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cloths/edit.html.erb
<h1>Editing Cloth</h1>

<%= render 'form', cloth: @cloth %>

<%= link_to 'Show', @cloth %> |
<%= link_to 'Back', cloths_path %>

app/views/cloths/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cloths</h1>

<% form_tag(:action => :index) do %>
  <%= select_tag "brand", options_for_select(@brands) %>
  <%= submit_tag "Filter" %>
<% end %>
<% form_tag(:action => :index) do %>
  <%= select_tag "clothing_type", options_for_select(@clothing_types) %>
  <%= submit_tag "Filter" %>
<% end %>
<form method="GET" action="/cloths">
  descripcion: <input type="text" name="filter" />
  <input type="submit" />
</form>


<table>
  <thead>
    <tr>
      <th><%= link_to "Name", cloths_path(:sort => true, :by => "Name", :order => (params[:order] == "asc" ? "desc" : "asc")) %></th>
      <th><%= link_to "Color", cloths_path(:sort => true, :by => "Color", :order => (params[:order] == "asc" ? "desc" : "asc")) %></th>
      <th><%= link_to "Description", cloths_path(:sort => true, :by => "Description", :order => (params[:order] == "asc" ? "desc" : "asc")) %></th>
      <th><%= link_to "Clothing type", cloths_path(:sort => true, :by => "Clothing_type", :order => (params[:order] == "asc" ? "desc" : "asc")) %></th>
      <th><%= link_to "Brand", cloths_path(:sort => true, :by => "Brand", :order => (params[:order] == "asc" ? "desc" : "asc")) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cloths.each do |cloth| %>
      <tr>
        <td><%= cloth.name %></td>
        <td><%= cloth.color %></td>
        <td><%= cloth.description %></td>
        <td><%= cloth.clothing_type.name %></td>
        <td><%= cloth.brand.name %></td>
        <td><%= link_to 'Show', cloth %></td>
        <td><%= link_to 'Edit', edit_cloth_path(cloth) %></td>
        <td><%= link_to 'Destroy', cloth, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @users %>

<br>

<%= link_to 'New Cloth', new_cloth_path %>

app/views/cloths/new.html.erb
<h1>New Cloth</h1>

<%= render 'form', cloth: @cloth %>

<%= link_to 'Back', cloths_path %>

app/views/cloths/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cloth.name %>
</p>

<p>
  <strong>Color:</strong>
  <%= @cloth.color %>
</p>

<p>
  <strong>Description:</strong>
  <%= @cloth.description %>
</p>

<p>
  <strong>Clothing type:</strong>
  <%= @cloth.clothing_type_id %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @cloth.brand_id %>
</p>

<%= link_to 'Edit', edit_cloth_path(@cloth) %> |
<%= link_to 'Back', cloths_path %>